#Module Manifest for Lab Support Scripts
#Generated by: Michael Dzikowski
@{
    ModuleVersion='1.2'
    GUID='6b16d89d-245f-47c5-a50a-a3d9445a21a6'
    Author='Michael Dzikowski'
    Copyright='(CC BY-NC 4.0) 2017-2021 Michael Dzikowski'
    Description='Lab Support Scripts for CIS256/CIS257 Schenectady County Community College'
    NestedModules=@('lss_OU.psm1','lss_US.psm1','lss_GR.psm1','lss_UG.psm1')
    PrivateData=@{
        PSData=@{
            LicenseUri='https://creativecommons.org/by-nc/4.0/legalcode'
        }
    }
}